apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod  # This is the name referenced in issuerRef.name
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  # Let's Encrypt API
    email: vinodhiniprabakaran21@gmail.com  # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-prod-key  # Secret to store ACME account's private key
    solvers:
      - http01:
          ingress:
            class: nginx  # Use Nginx ingress controller for HTTP-01 challenge

